# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QFrame, QGridLayout, QGroupBox, QHBoxLayout,
    QHeaderView, QLabel, QLayout, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QSpinBox,
    QStatusBar, QTabWidget, QTableWidget, QTableWidgetItem,
    QToolBox, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1188, 789)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tab_control = QWidget()
        self.tab_control.setObjectName(u"tab_control")
        self.gridLayout_2 = QGridLayout(self.tab_control)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.groupBox_2 = QGroupBox(self.tab_control)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setMinimumSize(QSize(550, 130))
        self.groupBox_2.setMaximumSize(QSize(16777215, 130))
        self.btn_startStop = QPushButton(self.groupBox_2)
        self.btn_startStop.setObjectName(u"btn_startStop")
        self.btn_startStop.setGeometry(QRect(430, 40, 103, 33))
        self.btn_startStop.setStyleSheet(u"color: rgb(0, 170, 0);")
        icon = QIcon()
        icon.addFile(u"play.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_startStop.setIcon(icon)
        self.btn_startStop.setCheckable(True)
        self.btn_startStop.setFlat(False)
        self.btn_connect = QPushButton(self.groupBox_2)
        self.btn_connect.setObjectName(u"btn_connect")
        self.btn_connect.setGeometry(QRect(270, 40, 103, 33))
        self.btn_connect.setCheckable(True)
        self.btn_connect.setChecked(False)
        self.cmbBox_ports = QComboBox(self.groupBox_2)
        self.cmbBox_ports.setObjectName(u"cmbBox_ports")
        self.cmbBox_ports.setGeometry(QRect(10, 40, 141, 32))
        self.btn_refreshPorts = QPushButton(self.groupBox_2)
        self.btn_refreshPorts.setObjectName(u"btn_refreshPorts")
        self.btn_refreshPorts.setGeometry(QRect(160, 40, 103, 33))
        icon1 = QIcon()
        iconThemeName = u"system-reboot"
        if QIcon.hasThemeIcon(iconThemeName):
            icon1 = QIcon.fromTheme(iconThemeName)
        else:
            icon1.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)

        self.btn_refreshPorts.setIcon(icon1)
        self.lbl_model = QLabel(self.groupBox_2)
        self.lbl_model.setObjectName(u"lbl_model")
        self.lbl_model.setGeometry(QRect(160, 80, 371, 31))
        self.btn_trigger = QPushButton(self.groupBox_2)
        self.btn_trigger.setObjectName(u"btn_trigger")
        self.btn_trigger.setGeometry(QRect(10, 80, 103, 33))
        self.btn_trigger.setCheckable(False)
        self.btn_trigger.setChecked(False)

        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.groupBox_3 = QGroupBox(self.tab_control)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setMinimumSize(QSize(550, 560))
        self.gridLayout_5 = QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.groupBox = QGroupBox(self.groupBox_3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setMinimumSize(QSize(0, 180))
        self.groupBox.setMaximumSize(QSize(16777215, 180))
        self.lbl_mode = QLabel(self.groupBox)
        self.lbl_mode.setObjectName(u"lbl_mode")
        self.lbl_mode.setGeometry(QRect(100, 140, 141, 24))
        self.lbl_runtime_out = QLabel(self.groupBox)
        self.lbl_runtime_out.setObjectName(u"lbl_runtime_out")
        self.lbl_runtime_out.setGeometry(QRect(290, 50, 81, 24))
        self.lbl_power_out = QLabel(self.groupBox)
        self.lbl_power_out.setObjectName(u"lbl_power_out")
        self.lbl_power_out.setGeometry(QRect(100, 110, 81, 24))
        self.lbl_charge_out = QLabel(self.groupBox)
        self.lbl_charge_out.setObjectName(u"lbl_charge_out")
        self.lbl_charge_out.setGeometry(QRect(290, 80, 81, 24))
        self.lbl_energy_out = QLabel(self.groupBox)
        self.lbl_energy_out.setObjectName(u"lbl_energy_out")
        self.lbl_energy_out.setGeometry(QRect(290, 110, 81, 24))
        self.lbl_desc_6 = QLabel(self.groupBox)
        self.lbl_desc_6.setObjectName(u"lbl_desc_6")
        self.lbl_desc_6.setGeometry(QRect(200, 110, 71, 24))
        self.lbl_desc_4 = QLabel(self.groupBox)
        self.lbl_desc_4.setObjectName(u"lbl_desc_4")
        self.lbl_desc_4.setGeometry(QRect(200, 50, 71, 24))
        self.lbl_desc_7 = QLabel(self.groupBox)
        self.lbl_desc_7.setObjectName(u"lbl_desc_7")
        self.lbl_desc_7.setGeometry(QRect(10, 140, 81, 24))
        self.lbl_volt_out = QLabel(self.groupBox)
        self.lbl_volt_out.setObjectName(u"lbl_volt_out")
        self.lbl_volt_out.setGeometry(QRect(100, 50, 81, 24))
        self.lbl_desc = QLabel(self.groupBox)
        self.lbl_desc.setObjectName(u"lbl_desc")
        self.lbl_desc.setGeometry(QRect(10, 50, 61, 24))
        self.lbl_desc.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.btn_clearOut = QPushButton(self.groupBox)
        self.btn_clearOut.setObjectName(u"btn_clearOut")
        self.btn_clearOut.setGeometry(QRect(160, 10, 103, 33))
        self.cmbBox_outGraphSel = QComboBox(self.groupBox)
        self.cmbBox_outGraphSel.addItem("")
        self.cmbBox_outGraphSel.addItem("")
        self.cmbBox_outGraphSel.addItem("")
        self.cmbBox_outGraphSel.setObjectName(u"cmbBox_outGraphSel")
        self.cmbBox_outGraphSel.setGeometry(QRect(10, 10, 141, 32))
        self.lbl_desc_3 = QLabel(self.groupBox)
        self.lbl_desc_3.setObjectName(u"lbl_desc_3")
        self.lbl_desc_3.setGeometry(QRect(10, 110, 61, 24))
        self.lbl_desc_3.setStyleSheet(u"color: rgb(0, 170, 255);")
        self.lbl_desc_5 = QLabel(self.groupBox)
        self.lbl_desc_5.setObjectName(u"lbl_desc_5")
        self.lbl_desc_5.setGeometry(QRect(200, 80, 71, 24))
        self.lbl_current_out = QLabel(self.groupBox)
        self.lbl_current_out.setObjectName(u"lbl_current_out")
        self.lbl_current_out.setGeometry(QRect(100, 80, 81, 24))
        self.lbl_desc_2 = QLabel(self.groupBox)
        self.lbl_desc_2.setObjectName(u"lbl_desc_2")
        self.lbl_desc_2.setGeometry(QRect(10, 80, 61, 24))
        self.lbl_desc_2.setStyleSheet(u"color: rgb(170, 0, 0);")
        self.btn_export = QPushButton(self.groupBox)
        self.btn_export.setObjectName(u"btn_export")
        self.btn_export.setGeometry(QRect(280, 10, 101, 33))
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(390, 10, 131, 141))
        self.chk_show_power = QCheckBox(self.groupBox_4)
        self.chk_show_power.setObjectName(u"chk_show_power")
        self.chk_show_power.setGeometry(QRect(20, 100, 81, 31))
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.chk_show_power.sizePolicy().hasHeightForWidth())
        self.chk_show_power.setSizePolicy(sizePolicy1)
        self.chk_show_power.setIconSize(QSize(20, 20))
        self.chk_show_power.setChecked(True)
        self.chk_show_voltage = QCheckBox(self.groupBox_4)
        self.chk_show_voltage.setObjectName(u"chk_show_voltage")
        self.chk_show_voltage.setGeometry(QRect(20, 40, 91, 31))
        sizePolicy1.setHeightForWidth(self.chk_show_voltage.sizePolicy().hasHeightForWidth())
        self.chk_show_voltage.setSizePolicy(sizePolicy1)
        self.chk_show_voltage.setIconSize(QSize(20, 20))
        self.chk_show_voltage.setChecked(True)
        self.chk_show_current = QCheckBox(self.groupBox_4)
        self.chk_show_current.setObjectName(u"chk_show_current")
        self.chk_show_current.setGeometry(QRect(20, 70, 91, 31))
        sizePolicy1.setHeightForWidth(self.chk_show_current.sizePolicy().hasHeightForWidth())
        self.chk_show_current.setSizePolicy(sizePolicy1)
        self.chk_show_current.setIconSize(QSize(20, 20))
        self.chk_show_current.setChecked(True)

        self.gridLayout_5.addWidget(self.groupBox, 1, 0, 1, 1)

        self.widget_graph = QWidget(self.groupBox_3)
        self.widget_graph.setObjectName(u"widget_graph")
        self.verticalLayout = QVBoxLayout(self.widget_graph)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.layout_graph = QVBoxLayout()
        self.layout_graph.setSpacing(0)
        self.layout_graph.setObjectName(u"layout_graph")
        self.layout_graph.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.layout_graph.setContentsMargins(0, -1, -1, -1)

        self.verticalLayout.addLayout(self.layout_graph)


        self.gridLayout_5.addWidget(self.widget_graph, 0, 0, 1, 1)


        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 2, 1)

        self.toolBox = QToolBox(self.tab_control)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setMinimumSize(QSize(600, 0))
        self.toolBox.setMaximumSize(QSize(600, 16777215))
        self.toolBox.setFrameShape(QFrame.Box)
        self.toolBox.setFrameShadow(QFrame.Raised)
        self.page_11 = QWidget()
        self.page_11.setObjectName(u"page_11")
        self.page_11.setGeometry(QRect(0, 0, 596, 275))
        self.label_14 = QLabel(self.page_11)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 80, 111, 31))
        self.btn_memory_save = QPushButton(self.page_11)
        self.btn_memory_save.setObjectName(u"btn_memory_save")
        self.btn_memory_save.setGeometry(QRect(210, 80, 103, 33))
        self.val_memory_slot = QSpinBox(self.page_11)
        self.val_memory_slot.setObjectName(u"val_memory_slot")
        self.val_memory_slot.setGeometry(QRect(120, 80, 81, 32))
        self.val_memory_slot.setMinimum(0)
        self.val_memory_slot.setMaximum(99)
        self.cmbBox_stdModes = QComboBox(self.page_11)
        self.cmbBox_stdModes.addItem("")
        self.cmbBox_stdModes.addItem("")
        self.cmbBox_stdModes.addItem("")
        self.cmbBox_stdModes.addItem("")
        self.cmbBox_stdModes.addItem("")
        self.cmbBox_stdModes.setObjectName(u"cmbBox_stdModes")
        self.cmbBox_stdModes.setGeometry(QRect(10, 10, 191, 32))
        self.btn_memory_recall = QPushButton(self.page_11)
        self.btn_memory_recall.setObjectName(u"btn_memory_recall")
        self.btn_memory_recall.setGeometry(QRect(330, 80, 103, 33))
        self.val_stdSet = QDoubleSpinBox(self.page_11)
        self.val_stdSet.setObjectName(u"val_stdSet")
        self.val_stdSet.setGeometry(QRect(210, 10, 111, 32))
        self.val_stdSet.setDecimals(4)
        self.val_stdSet.setMaximum(7500.000000000000000)
        self.val_stdSet.setSingleStep(0.100000000000000)
        self.btn_setStd = QPushButton(self.page_11)
        self.btn_setStd.setObjectName(u"btn_setStd")
        self.btn_setStd.setGeometry(QRect(330, 10, 103, 33))
        self.toolBox.addItem(self.page_11, u"Basic Modes")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(0, 0, 96, 26))
        self.btn_batSet = QPushButton(self.page)
        self.btn_batSet.setObjectName(u"btn_batSet")
        self.btn_batSet.setGeometry(QRect(120, 210, 103, 33))
        self.label_11 = QLabel(self.page)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 90, 151, 31))
        self.val_battery_seconds = QSpinBox(self.page)
        self.val_battery_seconds.setObjectName(u"val_battery_seconds")
        self.val_battery_seconds.setGeometry(QRect(310, 130, 61, 32))
        self.val_battery_seconds.setMinimum(0)
        self.val_battery_seconds.setMaximum(59)
        self.val_battery_seconds.setValue(0)
        self.val_battery_voltage = QDoubleSpinBox(self.page)
        self.val_battery_voltage.setObjectName(u"val_battery_voltage")
        self.val_battery_voltage.setGeometry(QRect(170, 50, 121, 32))
        self.val_battery_voltage.setDecimals(4)
        self.val_battery_voltage.setMinimum(0.000100000000000)
        self.val_battery_voltage.setMaximum(120.000000000000000)
        self.label_12 = QLabel(self.page)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 130, 151, 31))
        self.val_battery_minutes = QSpinBox(self.page)
        self.val_battery_minutes.setObjectName(u"val_battery_minutes")
        self.val_battery_minutes.setGeometry(QRect(240, 130, 61, 32))
        self.val_battery_minutes.setMinimum(0)
        self.val_battery_minutes.setMaximum(59)
        self.val_battery_minutes.setValue(0)
        self.val_battery_current = QDoubleSpinBox(self.page)
        self.val_battery_current.setObjectName(u"val_battery_current")
        self.val_battery_current.setGeometry(QRect(170, 10, 121, 32))
        self.val_battery_current.setDecimals(4)
        self.val_battery_current.setMinimum(0.000100000000000)
        self.val_battery_current.setMaximum(30.000000000000000)
        self.val_battery_current.setSingleStep(0.100000000000000)
        self.val_battery_hours = QSpinBox(self.page)
        self.val_battery_hours.setObjectName(u"val_battery_hours")
        self.val_battery_hours.setGeometry(QRect(170, 130, 61, 32))
        self.val_battery_hours.setMinimum(0)
        self.val_battery_hours.setMaximum(99)
        self.val_battery_hours.setValue(0)
        self.label_9 = QLabel(self.page)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 10, 151, 31))
        self.btn_bat_recall = QPushButton(self.page)
        self.btn_bat_recall.setObjectName(u"btn_bat_recall")
        self.btn_bat_recall.setGeometry(QRect(10, 210, 103, 33))
        self.label_13 = QLabel(self.page)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 170, 81, 31))
        self.label_10 = QLabel(self.page)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 50, 151, 31))
        self.val_battery_capacity = QDoubleSpinBox(self.page)
        self.val_battery_capacity.setObjectName(u"val_battery_capacity")
        self.val_battery_capacity.setGeometry(QRect(170, 90, 121, 32))
        self.val_battery_capacity.setDecimals(4)
        self.val_battery_capacity.setMinimum(0.000100000000000)
        self.val_battery_capacity.setMaximum(9999.000000000000000)
        self.val_battery_capacity.setSingleStep(0.100000000000000)
        self.val_battery_capacity.setValue(1.000000000000000)
        self.val_battery_slot = QSpinBox(self.page)
        self.val_battery_slot.setObjectName(u"val_battery_slot")
        self.val_battery_slot.setGeometry(QRect(170, 170, 51, 32))
        self.val_battery_slot.setMinimum(1)
        self.val_battery_slot.setMaximum(10)
        self.toolBox.addItem(self.page, u"Battery Mode")
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 575, 350))
        self.gridLayout_4 = QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.table_list = QTableWidget(self.page_2)
        if (self.table_list.columnCount() < 3):
            self.table_list.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.table_list.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.table_list.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.table_list.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        if (self.table_list.rowCount() < 84):
            self.table_list.setRowCount(84)
        self.table_list.setObjectName(u"table_list")
        sizePolicy.setHeightForWidth(self.table_list.sizePolicy().hasHeightForWidth())
        self.table_list.setSizePolicy(sizePolicy)
        self.table_list.setMinimumSize(QSize(450, 200))
        self.table_list.setRowCount(84)
        self.table_list.setColumnCount(3)
        self.table_list.horizontalHeader().setCascadingSectionResizes(False)
        self.table_list.horizontalHeader().setDefaultSectionSize(170)
        self.table_list.horizontalHeader().setStretchLastSection(True)
        self.table_list.verticalHeader().setStretchLastSection(False)

        self.gridLayout_4.addWidget(self.table_list, 3, 0, 1, 5)

        self.btn_list_set = QPushButton(self.page_2)
        self.btn_list_set.setObjectName(u"btn_list_set")

        self.gridLayout_4.addWidget(self.btn_list_set, 0, 0, 1, 1)

        self.btn_list_clear_mark = QPushButton(self.page_2)
        self.btn_list_clear_mark.setObjectName(u"btn_list_clear_mark")

        self.gridLayout_4.addWidget(self.btn_list_clear_mark, 1, 4, 1, 1)

        self.label_18 = QLabel(self.page_2)
        self.label_18.setObjectName(u"label_18")

        self.gridLayout_4.addWidget(self.label_18, 1, 0, 1, 1)

        self.label_19 = QLabel(self.page_2)
        self.label_19.setObjectName(u"label_19")

        self.gridLayout_4.addWidget(self.label_19, 2, 0, 1, 1)

        self.btn_list_clear_all = QPushButton(self.page_2)
        self.btn_list_clear_all.setObjectName(u"btn_list_clear_all")

        self.gridLayout_4.addWidget(self.btn_list_clear_all, 2, 4, 1, 1)

        self.val_list_slot = QSpinBox(self.page_2)
        self.val_list_slot.setObjectName(u"val_list_slot")
        self.val_list_slot.setMinimum(1)
        self.val_list_slot.setMaximum(7)

        self.gridLayout_4.addWidget(self.val_list_slot, 1, 1, 1, 1)

        self.btn_list_recall = QPushButton(self.page_2)
        self.btn_list_recall.setObjectName(u"btn_list_recall")

        self.gridLayout_4.addWidget(self.btn_list_recall, 1, 2, 1, 1)

        self.val_list_loops = QSpinBox(self.page_2)
        self.val_list_loops.setObjectName(u"val_list_loops")
        self.val_list_loops.setMinimum(3)

        self.gridLayout_4.addWidget(self.val_list_loops, 2, 1, 1, 1)

        self.btn_list_validate = QPushButton(self.page_2)
        self.btn_list_validate.setObjectName(u"btn_list_validate")

        self.gridLayout_4.addWidget(self.btn_list_validate, 0, 1, 1, 1)

        self.toolBox.addItem(self.page_2, u"List Mode")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setGeometry(QRect(0, 0, 96, 26))
        self.val_ocp_slot = QSpinBox(self.page_3)
        self.val_ocp_slot.setObjectName(u"val_ocp_slot")
        self.val_ocp_slot.setGeometry(QRect(90, 10, 51, 32))
        self.val_ocp_slot.setMinimum(1)
        self.val_ocp_slot.setMaximum(10)
        self.btn_ocp_recall = QPushButton(self.page_3)
        self.btn_ocp_recall.setObjectName(u"btn_ocp_recall")
        self.btn_ocp_recall.setGeometry(QRect(160, 10, 103, 33))
        self.label_20 = QLabel(self.page_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 10, 76, 31))
        self.btn_ocp_set = QPushButton(self.page_3)
        self.btn_ocp_set.setObjectName(u"btn_ocp_set")
        self.btn_ocp_set.setGeometry(QRect(470, 10, 103, 33))
        self.val_ocp_on_voltage = QDoubleSpinBox(self.page_3)
        self.val_ocp_on_voltage.setObjectName(u"val_ocp_on_voltage")
        self.val_ocp_on_voltage.setGeometry(QRect(140, 50, 121, 32))
        self.val_ocp_on_voltage.setDecimals(4)
        self.val_ocp_on_voltage.setMinimum(0.000100000000000)
        self.val_ocp_on_voltage.setMaximum(120.000000000000000)
        self.label_21 = QLabel(self.page_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 50, 121, 31))
        self.label_22 = QLabel(self.page_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 90, 121, 31))
        self.val_ocp_on_delay_seconds = QDoubleSpinBox(self.page_3)
        self.val_ocp_on_delay_seconds.setObjectName(u"val_ocp_on_delay_seconds")
        self.val_ocp_on_delay_seconds.setGeometry(QRect(140, 90, 121, 32))
        self.val_ocp_on_delay_seconds.setDecimals(3)
        self.val_ocp_on_delay_seconds.setMaximum(99999.990000000005239)
        self.label_23 = QLabel(self.page_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 130, 121, 31))
        self.val_ocp_initial_current = QDoubleSpinBox(self.page_3)
        self.val_ocp_initial_current.setObjectName(u"val_ocp_initial_current")
        self.val_ocp_initial_current.setGeometry(QRect(140, 130, 121, 32))
        self.val_ocp_initial_current.setDecimals(4)
        self.val_ocp_initial_current.setMinimum(0.000000000000000)
        self.val_ocp_initial_current.setMaximum(30.000000000000000)
        self.val_ocp_initial_current.setSingleStep(0.100000000000000)
        self.val_ocp_initial_current.setValue(0.000000000000000)
        self.val_ocp_step_current = QDoubleSpinBox(self.page_3)
        self.val_ocp_step_current.setObjectName(u"val_ocp_step_current")
        self.val_ocp_step_current.setGeometry(QRect(140, 170, 121, 32))
        self.val_ocp_step_current.setDecimals(4)
        self.val_ocp_step_current.setMinimum(0.000100000000000)
        self.val_ocp_step_current.setMaximum(30.000000000000000)
        self.val_ocp_step_current.setSingleStep(0.100000000000000)
        self.label_24 = QLabel(self.page_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 170, 121, 31))
        self.val_ocp_step_delay_seconds = QDoubleSpinBox(self.page_3)
        self.val_ocp_step_delay_seconds.setObjectName(u"val_ocp_step_delay_seconds")
        self.val_ocp_step_delay_seconds.setGeometry(QRect(140, 210, 121, 32))
        self.val_ocp_step_delay_seconds.setDecimals(3)
        self.val_ocp_step_delay_seconds.setMaximum(999999.989999999990687)
        self.label_25 = QLabel(self.page_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 210, 121, 31))
        self.label_26 = QLabel(self.page_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(300, 170, 141, 31))
        self.val_ocp_off_current = QDoubleSpinBox(self.page_3)
        self.val_ocp_off_current.setObjectName(u"val_ocp_off_current")
        self.val_ocp_off_current.setGeometry(QRect(450, 170, 121, 32))
        self.val_ocp_off_current.setDecimals(4)
        self.val_ocp_off_current.setMinimum(0.000100000000000)
        self.val_ocp_off_current.setMaximum(30.000000000000000)
        self.val_ocp_off_current.setSingleStep(0.100000000000000)
        self.val_ocp_test_voltage = QDoubleSpinBox(self.page_3)
        self.val_ocp_test_voltage.setObjectName(u"val_ocp_test_voltage")
        self.val_ocp_test_voltage.setGeometry(QRect(450, 130, 121, 32))
        self.val_ocp_test_voltage.setDecimals(4)
        self.val_ocp_test_voltage.setMinimum(0.000100000000000)
        self.val_ocp_test_voltage.setMaximum(120.000000000000000)
        self.label_27 = QLabel(self.page_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(300, 130, 141, 31))
        self.val_ocp_max_over_current = QDoubleSpinBox(self.page_3)
        self.val_ocp_max_over_current.setObjectName(u"val_ocp_max_over_current")
        self.val_ocp_max_over_current.setGeometry(QRect(450, 50, 121, 32))
        self.val_ocp_max_over_current.setDecimals(4)
        self.val_ocp_max_over_current.setMinimum(0.000100000000000)
        self.val_ocp_max_over_current.setMaximum(30.000000000000000)
        self.val_ocp_max_over_current.setSingleStep(0.100000000000000)
        self.label_28 = QLabel(self.page_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(300, 50, 141, 31))
        self.val_ocp_min_over_current = QDoubleSpinBox(self.page_3)
        self.val_ocp_min_over_current.setObjectName(u"val_ocp_min_over_current")
        self.val_ocp_min_over_current.setGeometry(QRect(450, 90, 121, 32))
        self.val_ocp_min_over_current.setDecimals(4)
        self.val_ocp_min_over_current.setMinimum(0.000100000000000)
        self.val_ocp_min_over_current.setMaximum(30.000000000000000)
        self.val_ocp_min_over_current.setSingleStep(0.100000000000000)
        self.label_29 = QLabel(self.page_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(300, 90, 141, 31))
        self.btn_ocp_validate = QPushButton(self.page_3)
        self.btn_ocp_validate.setObjectName(u"btn_ocp_validate")
        self.btn_ocp_validate.setGeometry(QRect(360, 10, 103, 33))
        self.toolBox.addItem(self.page_3, u"Overcurrent protection test mode")
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.page_4.setGeometry(QRect(0, 0, 96, 26))
        self.label_30 = QLabel(self.page_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(320, 210, 131, 31))
        self.label_31 = QLabel(self.page_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(320, 170, 131, 31))
        self.val_opp_min_over_power = QDoubleSpinBox(self.page_4)
        self.val_opp_min_over_power.setObjectName(u"val_opp_min_over_power")
        self.val_opp_min_over_power.setGeometry(QRect(460, 90, 121, 32))
        self.val_opp_min_over_power.setDecimals(4)
        self.val_opp_min_over_power.setMinimum(0.010000000000000)
        self.val_opp_min_over_power.setMaximum(300.000000000000000)
        self.label_32 = QLabel(self.page_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 210, 121, 31))
        self.label_33 = QLabel(self.page_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(320, 50, 131, 31))
        self.val_opp_step_delay_seconds = QDoubleSpinBox(self.page_4)
        self.val_opp_step_delay_seconds.setObjectName(u"val_opp_step_delay_seconds")
        self.val_opp_step_delay_seconds.setGeometry(QRect(150, 210, 121, 32))
        self.val_opp_step_delay_seconds.setDecimals(3)
        self.val_opp_step_delay_seconds.setMaximum(9999999.990000000223517)
        self.label_34 = QLabel(self.page_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 130, 121, 31))
        self.label_35 = QLabel(self.page_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(20, 10, 76, 31))
        self.val_opp_on_voltage = QDoubleSpinBox(self.page_4)
        self.val_opp_on_voltage.setObjectName(u"val_opp_on_voltage")
        self.val_opp_on_voltage.setGeometry(QRect(150, 50, 121, 32))
        self.val_opp_on_voltage.setDecimals(4)
        self.val_opp_on_voltage.setMinimum(0.000100000000000)
        self.val_opp_on_voltage.setMaximum(120.000000000000000)
        self.val_opp_max_over_power = QDoubleSpinBox(self.page_4)
        self.val_opp_max_over_power.setObjectName(u"val_opp_max_over_power")
        self.val_opp_max_over_power.setGeometry(QRect(460, 50, 121, 32))
        self.val_opp_max_over_power.setDecimals(4)
        self.val_opp_max_over_power.setMinimum(0.010000000000000)
        self.val_opp_max_over_power.setMaximum(300.000000000000000)
        self.val_opp_initial_power = QDoubleSpinBox(self.page_4)
        self.val_opp_initial_power.setObjectName(u"val_opp_initial_power")
        self.val_opp_initial_power.setGeometry(QRect(150, 130, 121, 32))
        self.val_opp_initial_power.setDecimals(4)
        self.val_opp_initial_power.setMinimum(0.010000000000000)
        self.val_opp_initial_power.setMaximum(300.000000000000000)
        self.label_36 = QLabel(self.page_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 50, 121, 31))
        self.val_opp_off_power = QDoubleSpinBox(self.page_4)
        self.val_opp_off_power.setObjectName(u"val_opp_off_power")
        self.val_opp_off_power.setGeometry(QRect(460, 210, 121, 32))
        self.val_opp_off_power.setDecimals(4)
        self.val_opp_off_power.setMinimum(0.010000000000000)
        self.val_opp_off_power.setMaximum(300.000000000000000)
        self.label_37 = QLabel(self.page_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 90, 121, 31))
        self.val_opp_on_delay_seconds = QDoubleSpinBox(self.page_4)
        self.val_opp_on_delay_seconds.setObjectName(u"val_opp_on_delay_seconds")
        self.val_opp_on_delay_seconds.setGeometry(QRect(150, 90, 121, 32))
        self.val_opp_on_delay_seconds.setDecimals(3)
        self.val_opp_on_delay_seconds.setMaximum(99999999.989999994635582)
        self.val_opp_test_voltage = QDoubleSpinBox(self.page_4)
        self.val_opp_test_voltage.setObjectName(u"val_opp_test_voltage")
        self.val_opp_test_voltage.setGeometry(QRect(460, 170, 121, 32))
        self.val_opp_test_voltage.setDecimals(4)
        self.val_opp_test_voltage.setMinimum(0.000100000000000)
        self.val_opp_test_voltage.setMaximum(120.000000000000000)
        self.val_opp_step_power = QDoubleSpinBox(self.page_4)
        self.val_opp_step_power.setObjectName(u"val_opp_step_power")
        self.val_opp_step_power.setGeometry(QRect(150, 170, 121, 32))
        self.val_opp_step_power.setDecimals(4)
        self.val_opp_step_power.setMinimum(0.010000000000000)
        self.val_opp_step_power.setMaximum(300.000000000000000)
        self.btn_opp_set = QPushButton(self.page_4)
        self.btn_opp_set.setObjectName(u"btn_opp_set")
        self.btn_opp_set.setGeometry(QRect(480, 10, 103, 33))
        self.val_opp_slot = QSpinBox(self.page_4)
        self.val_opp_slot.setObjectName(u"val_opp_slot")
        self.val_opp_slot.setGeometry(QRect(100, 10, 51, 32))
        self.val_opp_slot.setMinimum(1)
        self.val_opp_slot.setMaximum(10)
        self.label_38 = QLabel(self.page_4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(320, 90, 131, 31))
        self.btn_opp_recall = QPushButton(self.page_4)
        self.btn_opp_recall.setObjectName(u"btn_opp_recall")
        self.btn_opp_recall.setGeometry(QRect(170, 10, 103, 33))
        self.label_39 = QLabel(self.page_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 170, 121, 31))
        self.label_40 = QLabel(self.page_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(320, 130, 131, 31))
        self.val_opp_current_range = QDoubleSpinBox(self.page_4)
        self.val_opp_current_range.setObjectName(u"val_opp_current_range")
        self.val_opp_current_range.setGeometry(QRect(460, 130, 121, 32))
        self.val_opp_current_range.setDecimals(4)
        self.val_opp_current_range.setMinimum(0.000100000000000)
        self.val_opp_current_range.setMaximum(30.000000000000000)
        self.btn_opp_validate = QPushButton(self.page_4)
        self.btn_opp_validate.setObjectName(u"btn_opp_validate")
        self.btn_opp_validate.setGeometry(QRect(370, 10, 103, 33))
        self.toolBox.addItem(self.page_4, u"Overpower protection test mode")
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.page_5.setGeometry(QRect(0, 0, 96, 26))
        self.label_41 = QLabel(self.page_5)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 10, 81, 31))
        self.label_42 = QLabel(self.page_5)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 50, 81, 31))
        self.label_43 = QLabel(self.page_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 90, 91, 31))
        self.label_44 = QLabel(self.page_5)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 130, 91, 31))
        self.val_dcv_voltage_1 = QDoubleSpinBox(self.page_5)
        self.val_dcv_voltage_1.setObjectName(u"val_dcv_voltage_1")
        self.val_dcv_voltage_1.setGeometry(QRect(110, 10, 121, 32))
        self.val_dcv_voltage_1.setDecimals(4)
        self.val_dcv_voltage_1.setMinimum(0.000100000000000)
        self.val_dcv_voltage_1.setMaximum(120.000000000000000)
        self.val_dcv_voltage_2 = QDoubleSpinBox(self.page_5)
        self.val_dcv_voltage_2.setObjectName(u"val_dcv_voltage_2")
        self.val_dcv_voltage_2.setGeometry(QRect(110, 50, 121, 32))
        self.val_dcv_voltage_2.setDecimals(4)
        self.val_dcv_voltage_2.setMinimum(0.000100000000000)
        self.val_dcv_voltage_2.setMaximum(120.000000000000000)
        self.val_dcv_frequency = QDoubleSpinBox(self.page_5)
        self.val_dcv_frequency.setObjectName(u"val_dcv_frequency")
        self.val_dcv_frequency.setGeometry(QRect(110, 90, 121, 32))
        self.val_dcv_frequency.setDecimals(4)
        self.val_dcv_frequency.setMinimum(0.001000000000000)
        self.val_dcv_frequency.setMaximum(15000.000000000000000)
        self.val_dcv_duty = QDoubleSpinBox(self.page_5)
        self.val_dcv_duty.setObjectName(u"val_dcv_duty")
        self.val_dcv_duty.setGeometry(QRect(110, 130, 121, 32))
        self.val_dcv_duty.setDecimals(4)
        self.val_dcv_duty.setMinimum(0.010000000000000)
        self.val_dcv_duty.setMaximum(100.000000000000000)
        self.btn_dcv_set = QPushButton(self.page_5)
        self.btn_dcv_set.setObjectName(u"btn_dcv_set")
        self.btn_dcv_set.setGeometry(QRect(10, 180, 103, 33))
        self.btn_dcv_validate = QPushButton(self.page_5)
        self.btn_dcv_validate.setObjectName(u"btn_dcv_validate")
        self.btn_dcv_validate.setGeometry(QRect(130, 180, 103, 33))
        self.toolBox.addItem(self.page_5, u"Constant voltage dynamic mode")
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.page_6.setGeometry(QRect(0, 0, 96, 26))
        self.btn_dcc_validate = QPushButton(self.page_6)
        self.btn_dcc_validate.setObjectName(u"btn_dcc_validate")
        self.btn_dcc_validate.setGeometry(QRect(130, 180, 103, 33))
        self.val_dcc_duty = QDoubleSpinBox(self.page_6)
        self.val_dcc_duty.setObjectName(u"val_dcc_duty")
        self.val_dcc_duty.setGeometry(QRect(110, 130, 121, 32))
        self.val_dcc_duty.setDecimals(4)
        self.val_dcc_duty.setMinimum(0.010000000000000)
        self.val_dcc_duty.setMaximum(100.000000000000000)
        self.label_45 = QLabel(self.page_6)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 130, 91, 31))
        self.label_46 = QLabel(self.page_6)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(10, 90, 91, 31))
        self.btn_dcc_set = QPushButton(self.page_6)
        self.btn_dcc_set.setObjectName(u"btn_dcc_set")
        self.btn_dcc_set.setGeometry(QRect(10, 180, 103, 33))
        self.val_dcc_frequency = QDoubleSpinBox(self.page_6)
        self.val_dcc_frequency.setObjectName(u"val_dcc_frequency")
        self.val_dcc_frequency.setGeometry(QRect(110, 90, 121, 32))
        self.val_dcc_frequency.setDecimals(4)
        self.val_dcc_frequency.setMinimum(0.001000000000000)
        self.val_dcc_frequency.setMaximum(15000.000000000000000)
        self.val_dcc_current_1 = QDoubleSpinBox(self.page_6)
        self.val_dcc_current_1.setObjectName(u"val_dcc_current_1")
        self.val_dcc_current_1.setGeometry(QRect(110, 10, 121, 32))
        self.val_dcc_current_1.setDecimals(4)
        self.val_dcc_current_1.setMinimum(0.000100000000000)
        self.val_dcc_current_1.setMaximum(30.000000000000000)
        self.val_dcc_current_1.setSingleStep(0.100000000000000)
        self.label_47 = QLabel(self.page_6)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(10, 10, 81, 31))
        self.label_48 = QLabel(self.page_6)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(10, 50, 81, 31))
        self.val_dcc_current_2 = QDoubleSpinBox(self.page_6)
        self.val_dcc_current_2.setObjectName(u"val_dcc_current_2")
        self.val_dcc_current_2.setGeometry(QRect(110, 50, 121, 32))
        self.val_dcc_current_2.setDecimals(4)
        self.val_dcc_current_2.setMinimum(0.000100000000000)
        self.val_dcc_current_2.setMaximum(30.000000000000000)
        self.val_dcc_current_2.setSingleStep(0.100000000000000)
        self.val_dcc_slope_1 = QDoubleSpinBox(self.page_6)
        self.val_dcc_slope_1.setObjectName(u"val_dcc_slope_1")
        self.val_dcc_slope_1.setGeometry(QRect(360, 10, 121, 32))
        self.val_dcc_slope_1.setDecimals(4)
        self.val_dcc_slope_1.setMinimum(0.000100000000000)
        self.val_dcc_slope_1.setMaximum(0.300000000000000)
        self.val_dcc_slope_1.setSingleStep(0.010000000000000)
        self.label_49 = QLabel(self.page_6)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(260, 10, 81, 31))
        self.val_dcc_slope_2 = QDoubleSpinBox(self.page_6)
        self.val_dcc_slope_2.setObjectName(u"val_dcc_slope_2")
        self.val_dcc_slope_2.setGeometry(QRect(360, 50, 121, 32))
        self.val_dcc_slope_2.setDecimals(4)
        self.val_dcc_slope_2.setMinimum(0.000100000000000)
        self.val_dcc_slope_2.setMaximum(0.300000000000000)
        self.val_dcc_slope_2.setSingleStep(0.010000000000000)
        self.label_50 = QLabel(self.page_6)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(260, 50, 81, 31))
        self.toolBox.addItem(self.page_6, u"Constant current dynamic mode")
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.page_7.setGeometry(QRect(0, 0, 96, 26))
        self.val_dcr_duty = QDoubleSpinBox(self.page_7)
        self.val_dcr_duty.setObjectName(u"val_dcr_duty")
        self.val_dcr_duty.setGeometry(QRect(130, 130, 121, 32))
        self.val_dcr_duty.setDecimals(4)
        self.val_dcr_duty.setMinimum(0.010000000000000)
        self.val_dcr_duty.setMaximum(100.000000000000000)
        self.btn_dcr_validate = QPushButton(self.page_7)
        self.btn_dcr_validate.setObjectName(u"btn_dcr_validate")
        self.btn_dcr_validate.setGeometry(QRect(150, 180, 103, 33))
        self.label_51 = QLabel(self.page_7)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(10, 130, 91, 31))
        self.label_52 = QLabel(self.page_7)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(10, 90, 91, 31))
        self.val_dcr_frequency = QDoubleSpinBox(self.page_7)
        self.val_dcr_frequency.setObjectName(u"val_dcr_frequency")
        self.val_dcr_frequency.setGeometry(QRect(130, 90, 121, 32))
        self.val_dcr_frequency.setDecimals(4)
        self.val_dcr_frequency.setMinimum(0.001000000000000)
        self.val_dcr_frequency.setMaximum(15000.000000000000000)
        self.btn_dcr_set = QPushButton(self.page_7)
        self.btn_dcr_set.setObjectName(u"btn_dcr_set")
        self.btn_dcr_set.setGeometry(QRect(10, 180, 103, 33))
        self.val_dcr_resistance_1 = QDoubleSpinBox(self.page_7)
        self.val_dcr_resistance_1.setObjectName(u"val_dcr_resistance_1")
        self.val_dcr_resistance_1.setGeometry(QRect(130, 10, 121, 32))
        self.val_dcr_resistance_1.setDecimals(4)
        self.val_dcr_resistance_1.setMinimum(0.050000000000000)
        self.val_dcr_resistance_1.setMaximum(7500.000000000000000)
        self.label_53 = QLabel(self.page_7)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(10, 10, 101, 31))
        self.label_54 = QLabel(self.page_7)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(10, 50, 111, 31))
        self.val_dcr_resistance_2 = QDoubleSpinBox(self.page_7)
        self.val_dcr_resistance_2.setObjectName(u"val_dcr_resistance_2")
        self.val_dcr_resistance_2.setGeometry(QRect(130, 50, 121, 32))
        self.val_dcr_resistance_2.setDecimals(4)
        self.val_dcr_resistance_2.setMinimum(0.050000000000000)
        self.val_dcr_resistance_2.setMaximum(7500.000000000000000)
        self.toolBox.addItem(self.page_7, u"Constant resistance dynamic mode")
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.page_8.setGeometry(QRect(0, 0, 96, 26))
        self.val_dcp_duty = QDoubleSpinBox(self.page_8)
        self.val_dcp_duty.setObjectName(u"val_dcp_duty")
        self.val_dcp_duty.setGeometry(QRect(110, 130, 121, 32))
        self.val_dcp_duty.setDecimals(4)
        self.val_dcp_duty.setMinimum(0.010000000000000)
        self.val_dcp_duty.setMaximum(100.000000000000000)
        self.btn_dcp_validate = QPushButton(self.page_8)
        self.btn_dcp_validate.setObjectName(u"btn_dcp_validate")
        self.btn_dcp_validate.setGeometry(QRect(130, 180, 103, 33))
        self.label_55 = QLabel(self.page_8)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(10, 130, 91, 31))
        self.label_56 = QLabel(self.page_8)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(10, 90, 91, 31))
        self.val_dcp_frequency = QDoubleSpinBox(self.page_8)
        self.val_dcp_frequency.setObjectName(u"val_dcp_frequency")
        self.val_dcp_frequency.setGeometry(QRect(110, 90, 121, 32))
        self.val_dcp_frequency.setDecimals(4)
        self.val_dcp_frequency.setMinimum(0.001000000000000)
        self.val_dcp_frequency.setMaximum(15000.000000000000000)
        self.btn_dcp_set = QPushButton(self.page_8)
        self.btn_dcp_set.setObjectName(u"btn_dcp_set")
        self.btn_dcp_set.setGeometry(QRect(10, 180, 103, 33))
        self.val_dcp_power_1 = QDoubleSpinBox(self.page_8)
        self.val_dcp_power_1.setObjectName(u"val_dcp_power_1")
        self.val_dcp_power_1.setGeometry(QRect(110, 10, 121, 32))
        self.val_dcp_power_1.setDecimals(4)
        self.val_dcp_power_1.setMinimum(0.010000000000000)
        self.val_dcp_power_1.setMaximum(300.000000000000000)
        self.label_57 = QLabel(self.page_8)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(10, 10, 81, 31))
        self.label_58 = QLabel(self.page_8)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(10, 50, 81, 31))
        self.val_dcp_power_2 = QDoubleSpinBox(self.page_8)
        self.val_dcp_power_2.setObjectName(u"val_dcp_power_2")
        self.val_dcp_power_2.setGeometry(QRect(110, 50, 121, 32))
        self.val_dcp_power_2.setDecimals(4)
        self.val_dcp_power_2.setMinimum(0.010000000000000)
        self.val_dcp_power_2.setMaximum(150.000000000000000)
        self.toolBox.addItem(self.page_8, u"constant power dynamic mode")
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.page_9.setGeometry(QRect(0, 0, 96, 26))
        self.btn_pulse_validate = QPushButton(self.page_9)
        self.btn_pulse_validate.setObjectName(u"btn_pulse_validate")
        self.btn_pulse_validate.setGeometry(QRect(130, 130, 103, 33))
        self.btn_pulse_set = QPushButton(self.page_9)
        self.btn_pulse_set.setObjectName(u"btn_pulse_set")
        self.btn_pulse_set.setGeometry(QRect(10, 130, 103, 33))
        self.val_pulse_current_1 = QDoubleSpinBox(self.page_9)
        self.val_pulse_current_1.setObjectName(u"val_pulse_current_1")
        self.val_pulse_current_1.setGeometry(QRect(110, 10, 121, 32))
        self.val_pulse_current_1.setDecimals(4)
        self.val_pulse_current_1.setMinimum(0.000100000000000)
        self.val_pulse_current_1.setMaximum(30.000000000000000)
        self.val_pulse_current_1.setSingleStep(0.100000000000000)
        self.label_61 = QLabel(self.page_9)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(10, 10, 81, 31))
        self.label_62 = QLabel(self.page_9)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(10, 50, 81, 31))
        self.val_pulse_current_2 = QDoubleSpinBox(self.page_9)
        self.val_pulse_current_2.setObjectName(u"val_pulse_current_2")
        self.val_pulse_current_2.setGeometry(QRect(110, 50, 121, 32))
        self.val_pulse_current_2.setDecimals(4)
        self.val_pulse_current_2.setMinimum(0.000100000000000)
        self.val_pulse_current_2.setMaximum(30.000000000000000)
        self.val_pulse_current_2.setSingleStep(0.100000000000000)
        self.val_pulse_slope_2 = QDoubleSpinBox(self.page_9)
        self.val_pulse_slope_2.setObjectName(u"val_pulse_slope_2")
        self.val_pulse_slope_2.setGeometry(QRect(360, 50, 121, 32))
        self.val_pulse_slope_2.setDecimals(4)
        self.val_pulse_slope_2.setMinimum(0.000100000000000)
        self.val_pulse_slope_2.setMaximum(0.300000000000000)
        self.label_63 = QLabel(self.page_9)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(260, 10, 81, 31))
        self.label_64 = QLabel(self.page_9)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(260, 50, 81, 31))
        self.val_pulse_slope_1 = QDoubleSpinBox(self.page_9)
        self.val_pulse_slope_1.setObjectName(u"val_pulse_slope_1")
        self.val_pulse_slope_1.setGeometry(QRect(360, 10, 121, 32))
        self.val_pulse_slope_1.setDecimals(4)
        self.val_pulse_slope_1.setMinimum(0.000100000000000)
        self.val_pulse_slope_1.setMaximum(0.300000000000000)
        self.val_pulse_duration = QDoubleSpinBox(self.page_9)
        self.val_pulse_duration.setObjectName(u"val_pulse_duration")
        self.val_pulse_duration.setGeometry(QRect(110, 90, 121, 32))
        self.val_pulse_duration.setDecimals(4)
        self.val_pulse_duration.setMaximum(9999.989999999999782)
        self.label_69 = QLabel(self.page_9)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(10, 90, 81, 31))
        self.toolBox.addItem(self.page_9, u"Pulse dynamic mode")
        self.page_10 = QWidget()
        self.page_10.setObjectName(u"page_10")
        self.page_10.setGeometry(QRect(0, 0, 96, 26))
        self.btn_toggle_set = QPushButton(self.page_10)
        self.btn_toggle_set.setObjectName(u"btn_toggle_set")
        self.btn_toggle_set.setGeometry(QRect(20, 110, 103, 33))
        self.val_toggle_current_2 = QDoubleSpinBox(self.page_10)
        self.val_toggle_current_2.setObjectName(u"val_toggle_current_2")
        self.val_toggle_current_2.setGeometry(QRect(120, 60, 121, 32))
        self.val_toggle_current_2.setDecimals(4)
        self.val_toggle_current_2.setMinimum(0.000100000000000)
        self.val_toggle_current_2.setMaximum(0.300000000000000)
        self.val_toggle_slope_1 = QDoubleSpinBox(self.page_10)
        self.val_toggle_slope_1.setObjectName(u"val_toggle_slope_1")
        self.val_toggle_slope_1.setGeometry(QRect(370, 20, 121, 32))
        self.val_toggle_slope_1.setDecimals(4)
        self.val_toggle_slope_1.setMinimum(0.000100000000000)
        self.val_toggle_slope_1.setMaximum(0.300000000000000)
        self.label_65 = QLabel(self.page_10)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(270, 60, 81, 31))
        self.label_66 = QLabel(self.page_10)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(20, 20, 81, 31))
        self.val_toggle_slope_2 = QDoubleSpinBox(self.page_10)
        self.val_toggle_slope_2.setObjectName(u"val_toggle_slope_2")
        self.val_toggle_slope_2.setGeometry(QRect(370, 60, 121, 32))
        self.val_toggle_slope_2.setDecimals(4)
        self.val_toggle_slope_2.setMinimum(0.000100000000000)
        self.val_toggle_slope_2.setMaximum(0.300000000000000)
        self.label_67 = QLabel(self.page_10)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(270, 20, 81, 31))
        self.label_68 = QLabel(self.page_10)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(20, 60, 81, 31))
        self.btn_toggle_validate = QPushButton(self.page_10)
        self.btn_toggle_validate.setObjectName(u"btn_toggle_validate")
        self.btn_toggle_validate.setGeometry(QRect(140, 110, 103, 33))
        self.val_toggle_current_1 = QDoubleSpinBox(self.page_10)
        self.val_toggle_current_1.setObjectName(u"val_toggle_current_1")
        self.val_toggle_current_1.setGeometry(QRect(120, 20, 121, 32))
        self.val_toggle_current_1.setDecimals(4)
        self.val_toggle_current_1.setMinimum(0.000100000000000)
        self.val_toggle_current_1.setMaximum(30.000000000000000)
        self.toolBox.addItem(self.page_10, u"Toggle dynamic mode")

        self.gridLayout_2.addWidget(self.toolBox, 0, 1, 3, 1)

        self.gridLayout_2.setRowStretch(0, 20)
        self.gridLayout_2.setColumnStretch(0, 50)
        self.tabWidget.addTab(self.tab_control, "")
        self.tab_settings = QWidget()
        self.tab_settings.setObjectName(u"tab_settings")
        self.horizontalLayout = QHBoxLayout(self.tab_settings)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.groupBox_limits = QGroupBox(self.tab_settings)
        self.groupBox_limits.setObjectName(u"groupBox_limits")
        self.lbllimit = QLabel(self.groupBox_limits)
        self.lbllimit.setObjectName(u"lbllimit")
        self.lbllimit.setGeometry(QRect(10, 40, 111, 24))
        self.lbllimit_2 = QLabel(self.groupBox_limits)
        self.lbllimit_2.setObjectName(u"lbllimit_2")
        self.lbllimit_2.setGeometry(QRect(10, 80, 111, 24))
        self.lbllimit_3 = QLabel(self.groupBox_limits)
        self.lbllimit_3.setObjectName(u"lbllimit_3")
        self.lbllimit_3.setGeometry(QRect(10, 120, 131, 24))
        self.lbllimit_4 = QLabel(self.groupBox_limits)
        self.lbllimit_4.setObjectName(u"lbllimit_4")
        self.lbllimit_4.setGeometry(QRect(10, 160, 111, 24))
        self.val_maxVoltLimit = QDoubleSpinBox(self.groupBox_limits)
        self.val_maxVoltLimit.setObjectName(u"val_maxVoltLimit")
        self.val_maxVoltLimit.setGeometry(QRect(170, 40, 111, 32))
        self.val_maxVoltLimit.setAccelerated(False)
        self.val_maxVoltLimit.setDecimals(4)
        self.val_maxVoltLimit.setMinimum(0.000100000000000)
        self.val_maxVoltLimit.setMaximum(120.000000000000000)
        self.btn_setVoltLimit = QPushButton(self.groupBox_limits)
        self.btn_setVoltLimit.setObjectName(u"btn_setVoltLimit")
        self.btn_setVoltLimit.setGeometry(QRect(290, 40, 81, 33))
        self.btn_setCurrLimit = QPushButton(self.groupBox_limits)
        self.btn_setCurrLimit.setObjectName(u"btn_setCurrLimit")
        self.btn_setCurrLimit.setGeometry(QRect(290, 80, 81, 33))
        self.val_maxCurrLimit = QDoubleSpinBox(self.groupBox_limits)
        self.val_maxCurrLimit.setObjectName(u"val_maxCurrLimit")
        self.val_maxCurrLimit.setGeometry(QRect(170, 80, 111, 32))
        self.val_maxCurrLimit.setDecimals(4)
        self.val_maxCurrLimit.setMinimum(0.000100000000000)
        self.val_maxCurrLimit.setMaximum(30.000000000000000)
        self.btn_setResLimit = QPushButton(self.groupBox_limits)
        self.btn_setResLimit.setObjectName(u"btn_setResLimit")
        self.btn_setResLimit.setGeometry(QRect(290, 120, 81, 33))
        self.val_maxResLimit = QDoubleSpinBox(self.groupBox_limits)
        self.val_maxResLimit.setObjectName(u"val_maxResLimit")
        self.val_maxResLimit.setGeometry(QRect(170, 120, 111, 32))
        self.val_maxResLimit.setDecimals(4)
        self.val_maxResLimit.setMinimum(0.050000000000000)
        self.val_maxResLimit.setMaximum(7500.000000000000000)
        self.btn_setPowerLimit = QPushButton(self.groupBox_limits)
        self.btn_setPowerLimit.setObjectName(u"btn_setPowerLimit")
        self.btn_setPowerLimit.setGeometry(QRect(290, 160, 81, 33))
        self.val_maxPowerLimit = QDoubleSpinBox(self.groupBox_limits)
        self.val_maxPowerLimit.setObjectName(u"val_maxPowerLimit")
        self.val_maxPowerLimit.setGeometry(QRect(170, 160, 111, 32))
        self.val_maxPowerLimit.setDecimals(4)
        self.val_maxPowerLimit.setMinimum(0.010000000000000)
        self.val_maxPowerLimit.setMaximum(300.000000000000000)
        self.btn_resetLimits = QPushButton(self.groupBox_limits)
        self.btn_resetLimits.setObjectName(u"btn_resetLimits")
        self.btn_resetLimits.setGeometry(QRect(10, 200, 121, 33))
        self.btn_getLimits = QPushButton(self.groupBox_limits)
        self.btn_getLimits.setObjectName(u"btn_getLimits")
        self.btn_getLimits.setGeometry(QRect(170, 200, 111, 33))

        self.horizontalLayout.addWidget(self.groupBox_limits)

        self.groupBox_settings = QGroupBox(self.tab_settings)
        self.groupBox_settings.setObjectName(u"groupBox_settings")
        self.label = QLabel(self.groupBox_settings)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 141, 31))
        self.cmb_baudrate = QComboBox(self.groupBox_settings)
        self.cmb_baudrate.addItem("")
        self.cmb_baudrate.addItem("")
        self.cmb_baudrate.addItem("")
        self.cmb_baudrate.addItem("")
        self.cmb_baudrate.addItem("")
        self.cmb_baudrate.setObjectName(u"cmb_baudrate")
        self.cmb_baudrate.setGeometry(QRect(180, 30, 96, 32))
        self.btn_set_settings = QPushButton(self.groupBox_settings)
        self.btn_set_settings.setObjectName(u"btn_set_settings")
        self.btn_set_settings.setGeometry(QRect(250, 420, 81, 33))
        self.label_2 = QLabel(self.groupBox_settings)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 70, 141, 31))
        self.label_3 = QLabel(self.groupBox_settings)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 100, 141, 31))
        self.label_4 = QLabel(self.groupBox_settings)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 130, 141, 31))
        self.label_5 = QLabel(self.groupBox_settings)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 160, 191, 31))
        self.chk_beep = QCheckBox(self.groupBox_settings)
        self.chk_beep.setObjectName(u"chk_beep")
        self.chk_beep.setGeometry(QRect(220, 75, 31, 31))
        sizePolicy1.setHeightForWidth(self.chk_beep.sizePolicy().hasHeightForWidth())
        self.chk_beep.setSizePolicy(sizePolicy1)
        self.chk_beep.setIconSize(QSize(20, 20))
        self.btn_get_settings = QPushButton(self.groupBox_settings)
        self.btn_get_settings.setObjectName(u"btn_get_settings")
        self.btn_get_settings.setGeometry(QRect(160, 420, 81, 33))
        self.chk_lock = QCheckBox(self.groupBox_settings)
        self.chk_lock.setObjectName(u"chk_lock")
        self.chk_lock.setGeometry(QRect(220, 100, 30, 30))
        sizePolicy1.setHeightForWidth(self.chk_lock.sizePolicy().hasHeightForWidth())
        self.chk_lock.setSizePolicy(sizePolicy1)
        self.chk_lock.setIconSize(QSize(20, 20))
        self.chk_trigger = QCheckBox(self.groupBox_settings)
        self.chk_trigger.setObjectName(u"chk_trigger")
        self.chk_trigger.setGeometry(QRect(220, 130, 30, 30))
        sizePolicy1.setHeightForWidth(self.chk_trigger.sizePolicy().hasHeightForWidth())
        self.chk_trigger.setSizePolicy(sizePolicy1)
        self.chk_trigger.setStyleSheet(u"")
        self.chk_trigger.setIconSize(QSize(20, 20))
        self.chk_trigger.setChecked(False)
        self.chk_comp = QCheckBox(self.groupBox_settings)
        self.chk_comp.setObjectName(u"chk_comp")
        self.chk_comp.setGeometry(QRect(220, 160, 30, 30))
        sizePolicy1.setHeightForWidth(self.chk_comp.sizePolicy().hasHeightForWidth())
        self.chk_comp.setSizePolicy(sizePolicy1)
        self.chk_comp.setIconSize(QSize(20, 20))
        self.chk_dhcp = QCheckBox(self.groupBox_settings)
        self.chk_dhcp.setObjectName(u"chk_dhcp")
        self.chk_dhcp.setGeometry(QRect(220, 190, 30, 30))
        sizePolicy1.setHeightForWidth(self.chk_dhcp.sizePolicy().hasHeightForWidth())
        self.chk_dhcp.setSizePolicy(sizePolicy1)
        self.chk_dhcp.setIconSize(QSize(20, 20))
        self.label_6 = QLabel(self.groupBox_settings)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 190, 191, 31))
        self.btn_factory_reset = QPushButton(self.groupBox_settings)
        self.btn_factory_reset.setObjectName(u"btn_factory_reset")
        self.btn_factory_reset.setGeometry(QRect(10, 420, 121, 33))
        self.label_7 = QLabel(self.groupBox_settings)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 220, 91, 31))
        self.val_ip_address = QLineEdit(self.groupBox_settings)
        self.val_ip_address.setObjectName(u"val_ip_address")
        self.val_ip_address.setGeometry(QRect(170, 220, 151, 31))
        self.label_8 = QLabel(self.groupBox_settings)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 260, 101, 31))
        self.val_subnetmask = QLineEdit(self.groupBox_settings)
        self.val_subnetmask.setObjectName(u"val_subnetmask")
        self.val_subnetmask.setGeometry(QRect(170, 260, 151, 31))
        self.val_gateway = QLineEdit(self.groupBox_settings)
        self.val_gateway.setObjectName(u"val_gateway")
        self.val_gateway.setGeometry(QRect(170, 300, 151, 31))
        self.label_15 = QLabel(self.groupBox_settings)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 300, 101, 31))
        self.label_16 = QLabel(self.groupBox_settings)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 340, 111, 31))
        self.val_mac_address = QLineEdit(self.groupBox_settings)
        self.val_mac_address.setObjectName(u"val_mac_address")
        self.val_mac_address.setGeometry(QRect(170, 340, 151, 31))
        self.label_17 = QLabel(self.groupBox_settings)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 380, 111, 31))
        self.val_device_port = QSpinBox(self.groupBox_settings)
        self.val_device_port.setObjectName(u"val_device_port")
        self.val_device_port.setGeometry(QRect(170, 380, 151, 32))
        self.val_device_port.setMinimum(1)
        self.val_device_port.setMaximum(65535)
        self.btn_init_saves = QPushButton(self.groupBox_settings)
        self.btn_init_saves.setObjectName(u"btn_init_saves")
        self.btn_init_saves.setGeometry(QRect(10, 460, 121, 33))

        self.horizontalLayout.addWidget(self.groupBox_settings)

        self.groupBox_guisettings = QGroupBox(self.tab_settings)
        self.groupBox_guisettings.setObjectName(u"groupBox_guisettings")
        self.label_79 = QLabel(self.groupBox_guisettings)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(10, 50, 151, 31))
        self.chk_off_close = QCheckBox(self.groupBox_guisettings)
        self.chk_off_close.setObjectName(u"chk_off_close")
        self.chk_off_close.setGeometry(QRect(210, 50, 30, 30))
        sizePolicy1.setHeightForWidth(self.chk_off_close.sizePolicy().hasHeightForWidth())
        self.chk_off_close.setSizePolicy(sizePolicy1)
        self.chk_off_close.setIconSize(QSize(20, 20))
        self.btn_save_settings = QPushButton(self.groupBox_guisettings)
        self.btn_save_settings.setObjectName(u"btn_save_settings")
        self.btn_save_settings.setGeometry(QRect(180, 310, 101, 33))
        self.label_80 = QLabel(self.groupBox_guisettings)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(10, 220, 151, 31))
        self.val_measure_interval = QDoubleSpinBox(self.groupBox_guisettings)
        self.val_measure_interval.setObjectName(u"val_measure_interval")
        self.val_measure_interval.setGeometry(QRect(190, 220, 71, 32))
        self.val_measure_interval.setAccelerated(False)
        self.val_measure_interval.setDecimals(1)
        self.val_measure_interval.setMinimum(0.500000000000000)
        self.val_measure_interval.setMaximum(10.000000000000000)
        self.val_measure_interval.setSingleStep(0.100000000000000)
        self.val_measure_interval.setValue(1.000000000000000)
        self.label_81 = QLabel(self.groupBox_guisettings)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(10, 110, 151, 31))
        self.chk_serial_debug = QCheckBox(self.groupBox_guisettings)
        self.chk_serial_debug.setObjectName(u"chk_serial_debug")
        self.chk_serial_debug.setGeometry(QRect(210, 110, 30, 30))
        sizePolicy1.setHeightForWidth(self.chk_serial_debug.sizePolicy().hasHeightForWidth())
        self.chk_serial_debug.setSizePolicy(sizePolicy1)
        self.chk_serial_debug.setIconSize(QSize(20, 20))
        self.label_59 = QLabel(self.groupBox_guisettings)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(10, 260, 141, 31))
        self.cmb_baudrate_soft = QComboBox(self.groupBox_guisettings)
        self.cmb_baudrate_soft.addItem("")
        self.cmb_baudrate_soft.addItem("")
        self.cmb_baudrate_soft.addItem("")
        self.cmb_baudrate_soft.addItem("")
        self.cmb_baudrate_soft.addItem("")
        self.cmb_baudrate_soft.setObjectName(u"cmb_baudrate_soft")
        self.cmb_baudrate_soft.setGeometry(QRect(180, 260, 101, 32))
        self.label_82 = QLabel(self.groupBox_guisettings)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(10, 140, 151, 31))
        self.chk_crosshair = QCheckBox(self.groupBox_guisettings)
        self.chk_crosshair.setObjectName(u"chk_crosshair")
        self.chk_crosshair.setGeometry(QRect(210, 140, 30, 30))
        sizePolicy1.setHeightForWidth(self.chk_crosshair.sizePolicy().hasHeightForWidth())
        self.chk_crosshair.setSizePolicy(sizePolicy1)
        self.chk_crosshair.setIconSize(QSize(20, 20))
        self.val_graph_time = QDoubleSpinBox(self.groupBox_guisettings)
        self.val_graph_time.setObjectName(u"val_graph_time")
        self.val_graph_time.setGeometry(QRect(190, 180, 71, 32))
        self.val_graph_time.setAccelerated(False)
        self.val_graph_time.setDecimals(1)
        self.val_graph_time.setMinimum(2.000000000000000)
        self.val_graph_time.setMaximum(999.000000000000000)
        self.val_graph_time.setSingleStep(1.000000000000000)
        self.val_graph_time.setValue(2.000000000000000)
        self.label_83 = QLabel(self.groupBox_guisettings)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(10, 180, 151, 31))
        self.chk_off_disconnect = QCheckBox(self.groupBox_guisettings)
        self.chk_off_disconnect.setObjectName(u"chk_off_disconnect")
        self.chk_off_disconnect.setGeometry(QRect(210, 80, 21, 30))
        sizePolicy1.setHeightForWidth(self.chk_off_disconnect.sizePolicy().hasHeightForWidth())
        self.chk_off_disconnect.setSizePolicy(sizePolicy1)
        self.chk_off_disconnect.setIconSize(QSize(20, 20))
        self.label_84 = QLabel(self.groupBox_guisettings)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(10, 80, 201, 31))

        self.horizontalLayout.addWidget(self.groupBox_guisettings)

        self.tabWidget.addTab(self.tab_settings, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.btn_startStop.setDefault(False)
        self.toolBox.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Main Controls", None))
        self.btn_startStop.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btn_connect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.cmbBox_ports.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Select Port", None))
        self.btn_refreshPorts.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.lbl_model.setText(QCoreApplication.translate("MainWindow", u"Model:", None))
        self.btn_trigger.setText(QCoreApplication.translate("MainWindow", u"Trigger", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Output", None))
        self.lbl_mode.setText(QCoreApplication.translate("MainWindow", u"none", None))
        self.lbl_runtime_out.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.lbl_power_out.setText(QCoreApplication.translate("MainWindow", u"0 W", None))
        self.lbl_charge_out.setText(QCoreApplication.translate("MainWindow", u"0 Ah", None))
        self.lbl_energy_out.setText(QCoreApplication.translate("MainWindow", u"0 Wh", None))
        self.lbl_desc_6.setText(QCoreApplication.translate("MainWindow", u"Energy", None))
        self.lbl_desc_4.setText(QCoreApplication.translate("MainWindow", u"Runtime", None))
        self.lbl_desc_7.setText(QCoreApplication.translate("MainWindow", u"Set mode", None))
        self.lbl_volt_out.setText(QCoreApplication.translate("MainWindow", u"0 V", None))
        self.lbl_desc.setText(QCoreApplication.translate("MainWindow", u"Voltage", None))
        self.btn_clearOut.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.cmbBox_outGraphSel.setItemText(0, QCoreApplication.translate("MainWindow", u"Voltage", None))
        self.cmbBox_outGraphSel.setItemText(1, QCoreApplication.translate("MainWindow", u"Current", None))
        self.cmbBox_outGraphSel.setItemText(2, QCoreApplication.translate("MainWindow", u"Power", None))

        self.lbl_desc_3.setText(QCoreApplication.translate("MainWindow", u"Power", None))
        self.lbl_desc_5.setText(QCoreApplication.translate("MainWindow", u"Charge", None))
        self.lbl_current_out.setText(QCoreApplication.translate("MainWindow", u"0 A", None))
        self.lbl_desc_2.setText(QCoreApplication.translate("MainWindow", u"Current", None))
        self.btn_export.setText(QCoreApplication.translate("MainWindow", u"Export Data", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Show graphs", None))
        self.chk_show_power.setText(QCoreApplication.translate("MainWindow", u"Power", None))
        self.chk_show_voltage.setText(QCoreApplication.translate("MainWindow", u"Voltage", None))
        self.chk_show_current.setText(QCoreApplication.translate("MainWindow", u"Current", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Memory Slot", None))
        self.btn_memory_save.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.cmbBox_stdModes.setItemText(0, QCoreApplication.translate("MainWindow", u"Constant Current", None))
        self.cmbBox_stdModes.setItemText(1, QCoreApplication.translate("MainWindow", u"Constant Voltage", None))
        self.cmbBox_stdModes.setItemText(2, QCoreApplication.translate("MainWindow", u"Constant Resistance", None))
        self.cmbBox_stdModes.setItemText(3, QCoreApplication.translate("MainWindow", u"Constant Power", None))
        self.cmbBox_stdModes.setItemText(4, QCoreApplication.translate("MainWindow", u"Short", None))

        self.btn_memory_recall.setText(QCoreApplication.translate("MainWindow", u"Recall", None))
        self.val_stdSet.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.btn_setStd.setText(QCoreApplication.translate("MainWindow", u"SET", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_11), QCoreApplication.translate("MainWindow", u"Basic Modes", None))
        self.btn_batSet.setText(QCoreApplication.translate("MainWindow", u"SET", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"End Capacity", None))
        self.val_battery_seconds.setSuffix(QCoreApplication.translate("MainWindow", u" s", None))
        self.val_battery_voltage.setSuffix(QCoreApplication.translate("MainWindow", u" V", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"End Duration", None))
        self.val_battery_minutes.setSuffix(QCoreApplication.translate("MainWindow", u" m", None))
        self.val_battery_current.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.val_battery_hours.setSuffix(QCoreApplication.translate("MainWindow", u" h", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Discharge current", None))
        self.btn_bat_recall.setText(QCoreApplication.translate("MainWindow", u"Recall", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Save Slot", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"End Voltage", None))
        self.val_battery_capacity.setSuffix(QCoreApplication.translate("MainWindow", u" Ah", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QCoreApplication.translate("MainWindow", u"Battery Mode", None))
        ___qtablewidgetitem = self.table_list.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Current - A", None));
        ___qtablewidgetitem1 = self.table_list.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Slope - A/uS", None));
        ___qtablewidgetitem2 = self.table_list.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Duration - S", None));
        self.btn_list_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.btn_list_clear_mark.setText(QCoreApplication.translate("MainWindow", u"Clear marked", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Save Slot", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Repetitions", None))
        self.btn_list_clear_all.setText(QCoreApplication.translate("MainWindow", u"Clear all", None))
        self.btn_list_recall.setText(QCoreApplication.translate("MainWindow", u"Recall", None))
#if QT_CONFIG(tooltip)
        self.val_list_loops.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>While less than 3 repetitions work, getting a list with less from device will not return anything, resulting in an error</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btn_list_validate.setText(QCoreApplication.translate("MainWindow", u"Validate", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("MainWindow", u"List Mode", None))
        self.btn_ocp_recall.setText(QCoreApplication.translate("MainWindow", u"Recall", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Save Slot", None))
        self.btn_ocp_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.val_ocp_on_voltage.setSuffix(QCoreApplication.translate("MainWindow", u" V", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"On Voltage", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"On Delay", None))
        self.val_ocp_on_delay_seconds.setSuffix(QCoreApplication.translate("MainWindow", u" s", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Initial Current", None))
        self.val_ocp_initial_current.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.val_ocp_step_current.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Step Current", None))
        self.val_ocp_step_delay_seconds.setSuffix(QCoreApplication.translate("MainWindow", u" s", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Step Delay", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Off Current", None))
        self.val_ocp_off_current.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.val_ocp_test_voltage.setSuffix(QCoreApplication.translate("MainWindow", u" V", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"OCP Voltage", None))
        self.val_ocp_max_over_current.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"max overcurrent", None))
        self.val_ocp_min_over_current.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"min overcurrent", None))
        self.btn_ocp_validate.setText(QCoreApplication.translate("MainWindow", u"Validate", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QCoreApplication.translate("MainWindow", u"Overcurrent protection test mode", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Off Power", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"OPP Voltage", None))
        self.val_opp_min_over_power.setSuffix(QCoreApplication.translate("MainWindow", u" W", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Step Delay", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"max overpower", None))
        self.val_opp_step_delay_seconds.setSuffix(QCoreApplication.translate("MainWindow", u" s", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Initial Power", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Save Slot", None))
        self.val_opp_on_voltage.setSuffix(QCoreApplication.translate("MainWindow", u" V", None))
        self.val_opp_max_over_power.setSuffix(QCoreApplication.translate("MainWindow", u" W", None))
        self.val_opp_initial_power.setSuffix(QCoreApplication.translate("MainWindow", u" W", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"On Voltage", None))
        self.val_opp_off_power.setSuffix(QCoreApplication.translate("MainWindow", u" W", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"On Delay", None))
        self.val_opp_on_delay_seconds.setSuffix(QCoreApplication.translate("MainWindow", u" s", None))
        self.val_opp_test_voltage.setSuffix(QCoreApplication.translate("MainWindow", u" V", None))
        self.val_opp_step_power.setSuffix(QCoreApplication.translate("MainWindow", u" W", None))
        self.btn_opp_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"min overpower", None))
        self.btn_opp_recall.setText(QCoreApplication.translate("MainWindow", u"Recall", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Step Power", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"current range", None))
        self.val_opp_current_range.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.btn_opp_validate.setText(QCoreApplication.translate("MainWindow", u"Validate", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), QCoreApplication.translate("MainWindow", u"Overpower protection test mode", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Voltage 1", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Voltage 2", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Frequency", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Duty Cycle", None))
        self.val_dcv_voltage_1.setSuffix(QCoreApplication.translate("MainWindow", u" V", None))
        self.val_dcv_voltage_2.setSuffix(QCoreApplication.translate("MainWindow", u" V", None))
        self.val_dcv_frequency.setSuffix(QCoreApplication.translate("MainWindow", u" Hz", None))
        self.val_dcv_duty.setSuffix(QCoreApplication.translate("MainWindow", u" %", None))
        self.btn_dcv_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.btn_dcv_validate.setText(QCoreApplication.translate("MainWindow", u"Validate", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), QCoreApplication.translate("MainWindow", u"Constant voltage dynamic mode", None))
        self.btn_dcc_validate.setText(QCoreApplication.translate("MainWindow", u"Validate", None))
        self.val_dcc_duty.setSuffix(QCoreApplication.translate("MainWindow", u" %", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Duty Cycle", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Frequency", None))
        self.btn_dcc_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.val_dcc_frequency.setSuffix(QCoreApplication.translate("MainWindow", u" Hz", None))
        self.val_dcc_current_1.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Current 1", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Current 2", None))
        self.val_dcc_current_2.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.val_dcc_slope_1.setSuffix(QCoreApplication.translate("MainWindow", u" A/uS", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Slope 1", None))
        self.val_dcc_slope_2.setSuffix(QCoreApplication.translate("MainWindow", u" A/uS", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Slope 2", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), QCoreApplication.translate("MainWindow", u"Constant current dynamic mode", None))
        self.val_dcr_duty.setSuffix(QCoreApplication.translate("MainWindow", u" %", None))
        self.btn_dcr_validate.setText(QCoreApplication.translate("MainWindow", u"Validate", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Duty Cycle", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Frequency", None))
        self.val_dcr_frequency.setSuffix(QCoreApplication.translate("MainWindow", u" Hz", None))
        self.btn_dcr_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.val_dcr_resistance_1.setSuffix(QCoreApplication.translate("MainWindow", u" \u03a9", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"Resistance 1", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"Resistance 2", None))
        self.val_dcr_resistance_2.setSuffix(QCoreApplication.translate("MainWindow", u" \u03a9", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), QCoreApplication.translate("MainWindow", u"Constant resistance dynamic mode", None))
        self.val_dcp_duty.setSuffix(QCoreApplication.translate("MainWindow", u" %", None))
        self.btn_dcp_validate.setText(QCoreApplication.translate("MainWindow", u"Validate", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Duty Cycle", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Frequency", None))
        self.val_dcp_frequency.setSuffix(QCoreApplication.translate("MainWindow", u" Hz", None))
        self.btn_dcp_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.val_dcp_power_1.setSuffix(QCoreApplication.translate("MainWindow", u" W", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Power 1", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"Power 2", None))
        self.val_dcp_power_2.setSuffix(QCoreApplication.translate("MainWindow", u" W", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), QCoreApplication.translate("MainWindow", u"constant power dynamic mode", None))
        self.btn_pulse_validate.setText(QCoreApplication.translate("MainWindow", u"Validate", None))
        self.btn_pulse_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.val_pulse_current_1.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"Current 1", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"Current 2", None))
        self.val_pulse_current_2.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.val_pulse_slope_2.setSuffix(QCoreApplication.translate("MainWindow", u" A/uS", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"Slope 1", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"Slope 2", None))
        self.val_pulse_slope_1.setSuffix(QCoreApplication.translate("MainWindow", u" A/uS", None))
        self.val_pulse_duration.setSuffix(QCoreApplication.translate("MainWindow", u" S", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"Duration", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), QCoreApplication.translate("MainWindow", u"Pulse dynamic mode", None))
        self.btn_toggle_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.val_toggle_current_2.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.val_toggle_slope_1.setSuffix(QCoreApplication.translate("MainWindow", u" A/uS", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"Slope 2", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"Current 1", None))
        self.val_toggle_slope_2.setSuffix(QCoreApplication.translate("MainWindow", u" A/uS", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"Slope 1", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"Current 2", None))
        self.btn_toggle_validate.setText(QCoreApplication.translate("MainWindow", u"Validate", None))
        self.val_toggle_current_1.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_10), QCoreApplication.translate("MainWindow", u"Toggle dynamic mode", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_control), QCoreApplication.translate("MainWindow", u"Control", None))
        self.groupBox_limits.setTitle(QCoreApplication.translate("MainWindow", u"Limit Values", None))
        self.lbllimit.setText(QCoreApplication.translate("MainWindow", u"Voltage limit", None))
        self.lbllimit_2.setText(QCoreApplication.translate("MainWindow", u"Current limit", None))
        self.lbllimit_3.setText(QCoreApplication.translate("MainWindow", u"Resistance limit", None))
        self.lbllimit_4.setText(QCoreApplication.translate("MainWindow", u"Power limit", None))
        self.val_maxVoltLimit.setSuffix(QCoreApplication.translate("MainWindow", u" V", None))
        self.btn_setVoltLimit.setText(QCoreApplication.translate("MainWindow", u"SET", None))
        self.btn_setCurrLimit.setText(QCoreApplication.translate("MainWindow", u"SET", None))
        self.val_maxCurrLimit.setSuffix(QCoreApplication.translate("MainWindow", u" A", None))
        self.btn_setResLimit.setText(QCoreApplication.translate("MainWindow", u"SET", None))
        self.val_maxResLimit.setSuffix(QCoreApplication.translate("MainWindow", u" \u03a9", None))
        self.btn_setPowerLimit.setText(QCoreApplication.translate("MainWindow", u"SET", None))
        self.val_maxPowerLimit.setSuffix(QCoreApplication.translate("MainWindow", u" W", None))
        self.btn_resetLimits.setText(QCoreApplication.translate("MainWindow", u"Reset Limits", None))
#if QT_CONFIG(tooltip)
        self.btn_getLimits.setToolTip(QCoreApplication.translate("MainWindow", u"Retrieve current limits from device", None))
#endif // QT_CONFIG(tooltip)
        self.btn_getLimits.setText(QCoreApplication.translate("MainWindow", u"Get Limits", None))
        self.groupBox_settings.setTitle(QCoreApplication.translate("MainWindow", u"Device Settings", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Serial - Baudrate", None))
        self.cmb_baudrate.setItemText(0, QCoreApplication.translate("MainWindow", u"9600", None))
        self.cmb_baudrate.setItemText(1, QCoreApplication.translate("MainWindow", u"19200", None))
        self.cmb_baudrate.setItemText(2, QCoreApplication.translate("MainWindow", u"38400", None))
        self.cmb_baudrate.setItemText(3, QCoreApplication.translate("MainWindow", u"57600", None))
        self.cmb_baudrate.setItemText(4, QCoreApplication.translate("MainWindow", u"115200", None))

        self.btn_set_settings.setText(QCoreApplication.translate("MainWindow", u"SET", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Beeping", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Key lock", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"External trigger", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Remote Compensation", None))
        self.chk_beep.setText("")
        self.btn_get_settings.setText(QCoreApplication.translate("MainWindow", u"GET", None))
        self.chk_lock.setText("")
        self.chk_trigger.setText("")
        self.chk_comp.setText("")
        self.chk_dhcp.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"DHCP", None))
        self.btn_factory_reset.setText(QCoreApplication.translate("MainWindow", u"Factory reset", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"IP address", None))
        self.val_ip_address.setInputMask(QCoreApplication.translate("MainWindow", u"000.000.000.000", None))
        self.val_ip_address.setText(QCoreApplication.translate("MainWindow", u"10.0.0.123", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Subnetmask", None))
        self.val_subnetmask.setInputMask(QCoreApplication.translate("MainWindow", u"000.000.000.000", None))
        self.val_subnetmask.setText(QCoreApplication.translate("MainWindow", u"255.255.255.0", None))
        self.val_gateway.setInputMask(QCoreApplication.translate("MainWindow", u"000.000.000.000", None))
        self.val_gateway.setText(QCoreApplication.translate("MainWindow", u"10.0.0.1", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Gateway", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Mac address", None))
        self.val_mac_address.setInputMask(QCoreApplication.translate("MainWindow", u"HH:HH:HH:HH:HH:HH", None))
        self.val_mac_address.setText(QCoreApplication.translate("MainWindow", u"01:80:41:ae:fd:7e", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.btn_init_saves.setText(QCoreApplication.translate("MainWindow", u"Init Saves", None))
        self.groupBox_guisettings.setTitle(QCoreApplication.translate("MainWindow", u"Program settings", None))
        self.label_79.setText(QCoreApplication.translate("MainWindow", u"Stop load on close", None))
        self.chk_off_close.setText("")
        self.btn_save_settings.setText(QCoreApplication.translate("MainWindow", u"SAVE", None))
        self.label_80.setText(QCoreApplication.translate("MainWindow", u"Measure interval", None))
        self.val_measure_interval.setSuffix(QCoreApplication.translate("MainWindow", u" s", None))
#if QT_CONFIG(tooltip)
        self.label_81.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>If enabled, sent and received data over serial is printed to console</p><p>Needs <span style=\" font-weight:600;\">reconnect</span> to take effect</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_81.setText(QCoreApplication.translate("MainWindow", u"Serial Debug Mode", None))
        self.chk_serial_debug.setText("")
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"Serial - Baudrate", None))
        self.cmb_baudrate_soft.setItemText(0, QCoreApplication.translate("MainWindow", u"9600", None))
        self.cmb_baudrate_soft.setItemText(1, QCoreApplication.translate("MainWindow", u"19200", None))
        self.cmb_baudrate_soft.setItemText(2, QCoreApplication.translate("MainWindow", u"38400", None))
        self.cmb_baudrate_soft.setItemText(3, QCoreApplication.translate("MainWindow", u"57600", None))
        self.cmb_baudrate_soft.setItemText(4, QCoreApplication.translate("MainWindow", u"115200", None))

        self.label_82.setText(QCoreApplication.translate("MainWindow", u"Enable crosshair", None))
        self.chk_crosshair.setText("")
        self.val_graph_time.setSuffix(QCoreApplication.translate("MainWindow", u" s", None))
        self.label_83.setText(QCoreApplication.translate("MainWindow", u"Graph timeframe", None))
        self.chk_off_disconnect.setText("")
        self.label_84.setText(QCoreApplication.translate("MainWindow", u"Stop load on disconnect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), QCoreApplication.translate("MainWindow", u"Settings", None))
    # retranslateUi

